# Generated by Django 4.2.5 on 2023-10-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='header',
            new_name='head',
        ),
    ]
