# Generated by Django 4.2.5 on 2023-10-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0002_rename_header_news_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='head',
            new_name='header',
        ),
    ]
